---
title: "Getting and Cleaning Data Course Project"
author: "José Tapiz Arrondo AKA José Francisco Tapiz Arrondo AKA Pachi Tapiz Arrondo AKA PTA AKA Diyeipetea"
date: "2025-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Code Book

## Introduction
This code book describes the variables, the data, and any transformations or work that was performed to clean up the data for the Human Activity Recognition Using Smartphones Dataset.

## Data Source
The data used in this project was obtained from the UCI Machine Learning Repository:
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Human Activity Recognition Using Smartphones Data Set
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## Data Description
```markdown
The dataset includes the following files:
- `features.txt`: List of all features.
- `activity_labels.txt`: Links the class labels with their activity name.
- `train/X_train.txt`: Training set.
- `train/y_train.txt`: Training labels.
- `test/X_test.txt`: Test set.
- `test/y_test.txt`: Test labels.
- `train/subject_train.txt`: Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.
- `test/subject_test.txt`: Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.
```

## Variables
The final tidy data set includes the following variables:
```markdown
- `subject`: The ID of the subject.
- `activity`: The activity performed by the subject.
- `timeBodyAccelerometerMeanX`: Mean of time domain body accelerometer signal in the X direction.
- `timeBodyAccelerometerMeanY`: Mean of time domain body accelerometer signal in the Y direction.
- `timeBodyAccelerometerMeanZ`: Mean of time domain body accelerometer signal in the Z direction.
- `timeBodyAccelerometerSTD...`: Standard deviation of time domain body accelerometer signal in the X, Y, and Z directions.
- `timeGravityAccelerometerMean...`: Mean of time domain gravity accelerometer signal in the X, Y, and Z directions.
- `timeBodyGyroscopeMean...`: Mean of time domain body gyroscope signal in the X, Y, and Z directions.
- `frequencyBodyAccelerometerMean...`: Mean of frequency domain body accelerometer signal in the X, Y, and Z directions.
- `frequencyBodyGyroscopeMean...`: Mean of frequency domain body gyroscope signal in the X, Y, and Z directions.
- (Include all other variables in a similar format)
```


## Summary
The final tidy data set contains the average of each variable for each activity and each subject. The data set is saved as `FinalData.txt`.

## Script
The R script `run_analysis.R` performs the data cleaning and transformation steps described above. The script is available in the GitHub repository.

1. **Download and unzip the dataset**:
   ```r
   if (!file.exists("UCI HAR Dataset")) {
     temp <- tempfile()
     download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip", temp)
     unzip(temp)
     unlink(temp)
   }
   ```

2. **Load the necessary libraries**:
   ```r
   library(dplyr)
   ```

3. **Read the data**:
   ```r
   features <- read.table("UCI HAR Dataset/features.txt", col.names = c("n", "functions"))
   activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("code", "activity"))
   subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
   x_test <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = features$functions)
   y_test <- read.table("UCI HAR Dataset/test/y_test.txt", col.names = "code")
   subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
   x_train <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = features$functions)
   y_train <- read.table("UCI HAR Dataset/train/y_train.txt", col.names = "code")
   ```
## Transformations
The following transformations were performed to clean up the data:

4. **Merge the training and the test sets to create one data set**:
   ```r
   X <- rbind(x_train, x_test)
   Y <- rbind(y_train, y_test)
   Subject <- rbind(subject_train, subject_test)
   Merged_Data <- cbind(Subject, Y, X)
   ```

5. **Extract only the measurements on the mean and standard deviation for each measurement**:
   ```r
   TidyData <- Merged_Data %>% select(subject, code, contains("mean"), contains("std"))
   ```

6. **Use descriptive activity names to name the activities in the data set**:
   ```r
   TidyData$code <- activities[TidyData$code, 2]
   ```

7. **Appropriately label the data set with descriptive variable names**:
   ```r
   names(TidyData)[2] = "activity"
   names(TidyData) <- gsub("Acc", "Accelerometer", names(TidyData))
   names(TidyData) <- gsub("Gyro", "Gyroscope", names(TidyData))
   names(TidyData) <- gsub("BodyBody", "Body", names(TidyData))
   names(TidyData) <- gsub("Mag", "Magnitude", names(TidyData))
   names(TidyData) <- gsub("^t", "Time", names(TidyData))
   names(TidyData) <- gsub("^f", "Frequency", names(TidyData))
   names(TidyData) <- gsub("tBody", "TimeBody", names(TidyData))
   names(TidyData) <- gsub("-mean()", "Mean", names(TidyData), ignore.case = TRUE)
   names(TidyData) <- gsub("-std()", "STD", names(TidyData), ignore.case = TRUE)
   names(TidyData) <- gsub("-freq()", "Frequency", names(TidyData), ignore.case = TRUE)
   names(TidyData) <- gsub("angle", "Angle", names(TidyData))
   names(TidyData) <- gsub("gravity", "Gravity", names(TidyData))
   ```

8. **Create a second, independent tidy data set with the average of each variable for each activity and each subject**:
   ```r
   FinalData <- TidyData %>%
     group_by(subject, activity) %>%
     summarise_all(funs(mean))
   write.table(FinalData, "FinalData.txt", row.name=FALSE)
   ```



